Temos um Doodle com a disponibilidade de cada aluno.

In [8]:
import pandas as pd

df_doodle = pd.read_csv("doodle.csv")
df_doodle

,Nome do aluno,Seg 7:30 AM – 8:30 AM,Seg 8:00 AM – 9:00 AM,Seg 9:00 AM – 10:00 AM,Seg 10:00 AM – 11:00 AM,Seg 11:00 AM – 12:00 PM,Seg 1:00 PM – 2:00 PM,Seg 2:00 PM – 3:00 PM,Seg 3:00 PM – 4:00 PM,Seg 4:00 PM – 5:00 PM,...,Sex 7:30 AM – 8:30 AM,Sex 8:00 AM – 9:00 AM,Sex 9:00 AM – 10:00 AM,Sex 10:00 AM – 11:00 AM,Sex 11:00 AM – 12:00 PM,Sex 1:00 PM – 2:00 PM,Sex 2:00 PM – 3:00 PM,Sex 3:00 PM – 4:00 PM,Sex 4:00 PM – 5:00 PM,Sex 4:30 PM – 5:30 PM
0,Aluno 1,OK,OK,OK,OK,OK,NaN,NaN,NaN,NaN,...,OK,OK,OK,OK,OK,NaN,NaN,NaN,NaN,OK
1,Aluno 2,OK,OK,OK,OK,OK,OK,OK,OK,OK,...,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK
2,Aluno 3,NaN,NaN,OK,OK,OK,OK,OK,OK,OK,...,NaN,NaN,OK,OK,OK,OK,OK,OK,OK,OK
3,Aluno 4,NaN,NaN,NaN,OK,OK,OK,OK,NaN,NaN,...,NaN,NaN,NaN,OK,OK,OK,OK,NaN,NaN,NaN
4,Aluno 5,OK,OK,OK,OK,OK,OK,OK,OK,OK,...,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,Aluno 87,OK,OK,OK,OK,OK,NaN,OK,OK,OK,...,OK,OK,OK,OK,NaN,OK,OK,OK,OK,OK
87,Aluno 88,NaN,OK,OK,OK,OK,OK,OK,OK,OK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,Aluno 89,NaN,NaN,NaN,NaN,NaN,OK,OK,OK,OK,...,NaN,NaN,NaN,NaN,NaN,OK,OK,OK,OK,OK
89,Aluno 90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,OK,OK,OK,OK,OK
90,Aluno 91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,OK,OK,NaN,NaN,OK,OK,OK,OK,OK

Nosso objetivo é encontrar a quantidade minima de encontros de tal forma que todos os alunos possam participar de pelo menos um encontro.  Não precisando ser necessariamente a quantidade de encontros ótimo (ou seja, a menor possível).  Veja uma solução subótima para o problema:

In [6]:
horarios_encontros = []

while len(df_doodle) >0:
    #desconsiderando a coluna "Aluno", procura a coluna com maior quantida de OKs
    #cada coluna representa o horario
    maior_qnt_oks = 0
    for coluna_horario in df_doodle.columns[1:]:
        qtd_oks_coluna = df_doodle[coluna_horario].count()
        if qtd_oks_coluna > maior_qnt_oks :
            maior_qnt_oks = qtd_oks_coluna
            coluna_maior_qnt_oks = coluna_horario
            
    #a coluna com maior quantidade de ok é um dos horarios de encontro
    horarios_encontros.append(coluna_maior_qnt_oks)
    
    #filtra o DataFrame colocando apenas os alunos que não foram contemplados nesse horario
    #para a proxima iteração
    df_doodle = df_doodle[df_doodle[coluna_maior_qnt_oks] != "OK"]
    
    

print(horarios_encontros)
print(f"Quantidade de encontros: {len(horarios_encontros)}")

['Qua 10:00 AM – 11:00 AM', 'Sex 4:30 PM – 5:30 PM', 'Seg 8:00 AM – 9:00 AM', 'Seg 6:00 PM – 7:00 PM', 'Seg 7:30 AM – 8:30 AM', 'Seg 11:00 AM – 12:00 PM', 'Seg 4:30 PM – 5:30 PM']
Quantidade de encontros: 7